### PR TITLE
removed a tag inside Link tags, because there are created automatically

### PR DESCRIPTION
**Pull request by Nkiriobasi**
I found the Anchor tag inside the Link tag in just one file in the whole project, so I have removed and tested.

### CODE REVIEW

**Review by francis-robert — COMMENTED** [review]
Can we remove the empty fragments to return the contents directly in the links?

```diff
- <>
```

**Comment by Nkiriobasi** [comment]
Alright, I'll remove it but actually in the browser the fragments do not
render any tag.

**Comment by therungg** [comment]
Hey, thanks for the PR! Unfortunately, the linter does *not* like the changes, and i'm not exactly sure why (looks good to me). Would you mind looking into that?

**Comment by Nkiriobasi** [comment]
Alright I'll

**Comment by Nkiriobasi** [comment]
I reverted back to using the fragments, when the component renders the Link
tag alone is rendered, it does not create additional Dom elements. but
since we are using next 13, the anchor tag will be created automatically as
a child.

**Comment by therungg** [comment]
Merging, thanks! :)

**Pull request merged**
