### PR TITLE
[Bugfix] Fixed an issue with skeleton animations throwing an error

### PR DESCRIPTION
**Pull request by zoglo**
@therungg 

This should fix the skeleton animation throwing an error within console

### CODE REVIEW

**Review by francis-robert — COMMENTED** [review]
The additional div is unnecessary. To resolve the issue we only need to remove the `%` from the `viewBox` props in the skeletons. With `0 0 100 657` as we'd have we would be telling the SVG to use a coordinate system that starts at 0,0 and extends to 100,657. The width and height attributes and the CSS then control how that coordinate system is scaled to fit the actual size of the SVG on the page. In this case, the SVG will scale to 100% of its container's width and 657 pixels of height.

**Comment by zoglo** [comment]
Good point, might just need to remove the outer div @francis-robert .

Will do it soon.

Also no need on the viewbox itself as the SVG gets inline styles itself.
Having the viewbox would make it non-responsive again.

**Review by francis-robert — APPROVED** [review]
LGTM 🚀

**Comment by therungg** [comment]
This still gives some of the console errors as per the latest deployment. It's from the `calc()`'s.

image

Also, seems to still not render correctly there. Looks like (not coincidentally) it renders it at 100px height. Is this different on windows/different browser?

Ubuntu with firefox here

image

**Review by therungg — APPROVED** [review]

**Comment by therungg** [comment]
Thanks @zoglo !!

**Pull request merged**
